name: Ubuntu CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 23 * * 5"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Get Dependencies
      run: |
        sudo apt install flatpak-builder
        flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
    - name: Build
      run: |
        ./build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: flatpak-bundle
        path: ./*.flatpak

    - name: Create version string
      if: github.event_name == 'schedule'
      id: version
      run: echo "version=weekly-$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      if: github.event_name == 'schedule'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: Weekly Build ${{ steps.version.outputs.version }}
        prerelease: true
        files: ./Farming.flatpak
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}